name: Build

on:
  workflow_call:
    inputs:
      use-artifact:
        description: Upload built artifact if true
        required: true
        type: boolean
    outputs:
      artifact-name:
        description: Built artifact name
        value: ${{ jobs.build.outputs.artifact-name }}
      artifact-path:
        description: Built artifact path
        value: ${{ jobs.build.outputs.artifact-path }}

env:
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.artifact-name.outputs.VALUE }}
      artifact-path: ${{ steps.artifact-path.outputs.VALUE }}
    steps:
      - uses: actions/checkout@v3

      - id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions

      - id: node-modules-cache-key
        uses: ./.github/workflows/composite/node-modules-cache-key
        with:
          node-env: ${{ env.NODE_ENV }}
          node-version: ${{ steps.setup-node.outputs.node-version }}

      - uses: actions/cache@v3
        with:
          key: ${{ steps.node-modules-cache-key.outputs.key }}
          path: ${{ steps.node-modules-cache-key.outputs.path }}
          restore-keys: ${{ steps.node-modules-cache-key.outputs.restore-keys }}

      - run: yarn install --frozen-lockfile
        shell: bash

      - run: yarn run build
        shell: bash

      - id: artifact-name
        run: echo "VALUE=build-${GITHUB_SHA}" >> $GITHUB_OUTPUT
        shell: bash

      - id: artifact-path
        run: echo "VALUE=.output" >> $GITHUB_OUTPUT
        shell: bash

      - if: ${{ inputs.use-artifact == true }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact-name.outputs.VALUE }}
          path: ${{ steps.artifact-path.outputs.VALUE }}
          retention-days: 5
