name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

env:
  NODE_ENV: development

jobs:
  install-dependencies:
    needs: []
    uses: ./.github/workflows/_install-dependencies.yml
    with:
      node-env: development

  eslint:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.install-dependencies.outputs.node-version }}

      - uses: actions/cache/restore@v3
        with:
          key: ${{ needs.install-dependencies.outputs.node-modules-cache-key }}
          path: ${{ needs.install-dependencies.outputs.node-modules-cache-path }}

      - run: yarn run postinstall
        shell: bash

      - run: yarn run lint
        shell: bash

  coverage:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.install-dependencies.outputs.node-version }}

      - uses: actions/cache/restore@v3
        with:
          key: ${{ needs.install-dependencies.outputs.node-modules-cache-key }}
          path: ${{ needs.install-dependencies.outputs.node-modules-cache-path }}

      - run: yarn run postinstall
        shell: bash

      - run: yarn run coverage
        shell: bash

  build-app:
    needs: []
    uses: ./.github/workflows/_build-app.yml
    with:
      use-artifact: true

  check-built-app:
    needs: [build-app]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build-app.outputs.artifact-name }}
          path: ${{ needs.build-app.outputs.artifact-path }}

      - run: ls -a
        shell: bash
        working-directory: ${{ needs.build-app.outputs.artifact-path }}
